
export const rootPaths = {
  root: '/',
  pageRoot: 'pages',
  authRoot: 'authentication',
  errorRoot: 'error',
};

export default {
  dashboard: `/${rootPaths.pageRoot}/dashboard`,
  pettips: `/${rootPaths.pageRoot}/pettips`,
  petTipDetail: `/${rootPaths.pageRoot}/pettips/pettips-details/:tipId`,
  users: `/${rootPaths.pageRoot}/users`,
  events: `/${rootPaths.pageRoot}/upcoming-events`,
  eventDetails: `/${rootPaths.pageRoot}/upcoming-events/petevent-details/:eventId`,
  pets: `/${rootPaths.pageRoot}/pets`,
  petDetails: `/${rootPaths.pageRoot}/pets/pet-details/:petId`,
  mentors: `/${rootPaths.pageRoot}/mentors`,
  messages: `/${rootPaths.pageRoot}/messages`,
  settings: `/${rootPaths.pageRoot}/settings`,
  vlsRoot: `/${rootPaths.pageRoot}/vls`,
  vlsLawPractice: `/${rootPaths.pageRoot}/vls/law-practice`,
  vlsAibe: `/${rootPaths.pageRoot}/vls/aibe`,
  vlsAcademy: `/${rootPaths.pageRoot}/vls/academy`,
  management: `/${rootPaths.pageRoot}/management`,
  ramananFinancial: `/${rootPaths.pageRoot}/ramananFinancial`,
  ophthallWebinar: `/${rootPaths.pageRoot}/ophthall-webinar`,
  pixelEye: `/${rootPaths.pageRoot}/pixel-eye`,
  invictusRoot: `/${rootPaths.pageRoot}/invictus`,
  invictusLeads: `/${rootPaths.pageRoot}/invictus/leads`,
  invictusMeta: `/${rootPaths.pageRoot}/invictus/meta`,
  krInstitute: `/${rootPaths.pageRoot}/kr-institute`,
  mirraBuilders: `/${rootPaths.pageRoot}/mirra-builders`,
  naitrika: `/${rootPaths.pageRoot}/naitrika`,
  netralaya: `/${rootPaths.pageRoot}/netralaya`,
  wellinit: `/${rootPaths.pageRoot}/wellinit`,
  mahimmyFoods: `/${rootPaths.pageRoot}/mahimmy-foods`,
  signin: `/${rootPaths.authRoot}/signin`,
  forgotPassword: `/${rootPaths.authRoot}/forgot-password`,
  404: `/${rootPaths.errorRoot}/404`,
};